# This is a basic workflow to help you get started with Actions

name: RunPHP

# Controls when the action will run. 
on:
  # Triggers the workflow on push of repository
  push:
    branches: [ main ]
  # Can add a schedule cron of when to run action but leaving this commented out for now
  #schedule:
  #  - cron: '0 08 * * *' 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # PHP GitHub Action created by https://github.com/nanasess
    - uses: actions/checkout@master
    - uses: nanasess/setup-php@master
      with:
        php-version: '7.4'
    # This triggers our php file we created before
    - run: php ./converter.php
